# Generated by Django 4.1.2 on 2022-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_repeat",
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
    ]
