# Generated by Django 4.1.2 on 2022-11-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_password_repeat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password_repeat",
            field=models.CharField(max_length=128),
        ),
    ]
