version: '3.8'

services:

  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      - db
      - api
    networks:
      - todolist_front_network

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - ./:/code/
    networks:
      - todolist_front_network
      - todolist_db_network

  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
        DB_HOST: db
    volumes:
      - ./:/code/
    networks:
      - todolist_db_network
    command: >
      sh -c "python todolist/manage.py runbot"


  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "5432:5432"
    networks:
      - todolist_db_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:

networks:
  todolist_db_network:
  todolist_front_network: