# Generated by Django 4.0.1 on 2022-11-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='telegram_user_id',
        ),
        migrations.AddField(
            model_name='tguser',
            name='tg_chat_id',
            field=models.IntegerField(null=True, verbose_name='ID чата в телеграм'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='tg_user_id',
            field=models.IntegerField(null=True, verbose_name='ID пользователя в телеграм'),
        ),
    ]
